'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace NoxiusDefenderDisabler.Properties


    ''' <summary>
    '''   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    ''' </summary>
    ' StronglyTypedResourceBuilder generó automáticamente esta clase
    ' a través de una herramienta como ResGen o Visual Studio.
    ' Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    ' con la opción /str o recompile su proyecto de VS.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NoxiusDefenderDisabler.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property big_noxius As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("big-noxius", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property defender As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defender", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property discord As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discord", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property github As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("github", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
